

name: "智能助手"
description: "一个功能强大的智能助手"
system_prompt: "你是一个有用的AI助手，可以帮助用户解决各种问题。"

llm_config:
  provider: "deepseek"
  model_name: "deepseek-chat"
  model_parameters:
    temperature: 0.7
    max_tokens: 2048
  
# 工具配置
tools:
  - "web_search"

# 知识库配置
knowledge_config:
  enabled: true
  databases:
    - "kb_001"
    - "kb_002"
  retrieval_config:
    top_k: 5
    similarity_threshold: 0.8

# MCP技能配置
mcp_config:
  enabled: false
  servers:
    - "time_tools"
    - "system_tools"

