config_file: null
config_path: !!python/object/apply:pathlib.WindowsPath
- C:\
- Users
- admin
- github
- Yuxi-agent
- server
- config
- base_config.yaml
custom_models: []
embed_model: ollama/nomic-embed-text
enable_agent_management: true
enable_knowledge_base: true
enable_reranker: true
enable_web_search: true
model_configs: !!python/object:config.app_config.ModelConfigs
  __dict__:
    EMBED_MODEL_INFO:
      ollama/bge-base-en-v1.5: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/embed
          dimension: 768
          name: bge-base-en-v1.5
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      ollama/bge-large-en-v1.5: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/embed
          dimension: 1024
          name: bge-large-en-v1.5
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      ollama/bge-large-zh-v1.5: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/embed
          dimension: 1024
          name: bge-large-zh-v1.5
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      ollama/bge-m3: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/embed
          dimension: 1024
          name: bge-m3
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      ollama/bge-small-en-v1.5: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/embed
          dimension: 384
          name: bge-small-en-v1.5
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      ollama/nomic-embed-text: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/embed
          dimension: 768
          name: nomic-embed-text
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      siliconflow/BAAI/bge-m3: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: SILICONFLOW_API_KEY
          base_url: https://api.siliconflow.cn/v1/embeddings
          dimension: 1024
          name: BAAI/bge-m3
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      vllm/BAAI/bge-large-zh-v1.5: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: no_api_key
          base_url: http://localhost:8081/v1/embeddings
          dimension: 1024
          name: BAAI/bge-large-zh-v1.5
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
      vllm/Qwen/Qwen3-Embedding-0.6B: !!python/object:config.app_config.EmbedModel
        __dict__:
          api_key: no_api_key
          base_url: http://localhost:8081/v1/embeddings
          dimension: 1024
          name: Qwen3-Embedding-0.6B
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          dimension: null
          name: null
        __pydantic_private__: null
    MODEL_NAMES:
      ark: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: null
          base_url: https://ark.cn-beijing.volces.com/api/v3
          default: doubao-1-5-pro-32k-250115
          env:
          - ARK_API_KEY
          models:
          - doubao-1-5-pro-32k-250115
          - doubao-1-5-lite-32k-250115
          - doubao-1-5-pro-4k-250115
          - doubao-1-5-lite-4k-250115
          - deepseek-r1-250120
          name: 豆包（Ark）
          url: https://console.volcengine.com/ark/region:ark+cn-beijing/model
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      dashscope: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: null
          base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
          default: qwen-max-latest
          env:
          - DASHSCOPE_API_KEY
          models:
          - qwen-max-latest
          - qwen-max-longcontext
          - qwen3-235b-a22b
          - qwen3-32b
          - qwen2.5-7b-instruct
          - qwen2.5-32b-instruct
          - qwen2.5-72b-instruct
          - qwen2.5-7b-chat
          - qwen2.5-32b-chat
          - qwen2.5-72b-chat
          name: 阿里百炼 (DashScope)
          url: https://bailian.console.aliyun.com/?switchAgent=10226727&productCode=p_efm#/model-market
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      deepseek: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: sk-1c092f1fb0714f139019ae5f1ee8dad8
          base_url: https://api.deepseek.com/v1
          default: deepseek-chat
          env:
          - DEEPSEEK_API_KEY
          models:
          - deepseek-chat
          - deepseek-reasoner
          - deepseek-coder
          - deepseek-vision
          name: DeepSeek
          url: https://platform.deepseek.com/api-docs/zh-cn/pricing
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      lingyiwanwu: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: null
          base_url: https://api.lingyiwanwu.com/v1
          default: yi-large
          env:
          - LINGYIWANWU_API_KEY
          models:
          - yi-large
          - yi-large-turbo
          - yi-medium
          - yi-medium-turbo
          - yi-small
          - yi-small-turbo
          name: 零一万物 (Lingyiwanwu)
          url: https://platform.lingyiwanwu.com/
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      ollama: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: '123'
          base_url: http://localhost:11434/v1
          default: llama3.2
          env:
          - OLLAMA_API_KEY
          models:
          - llama3.2
          - llama3.2:3b
          - llama3.2:7b
          - llama3.2:70b
          - llama3.1
          - llama3.1:8b
          - llama3.1:70b
          - llama2
          - llama2:7b
          - llama2:13b
          - llama2:70b
          - qwen2.5
          - qwen2.5:7b
          - qwen2.5:32b
          - qwen2.5:72b
          - qwen2
          - qwen2:7b
          - qwen2:14b
          - qwen2:72b
          - mistral
          - mistral:7b
          - mistral:8x7b
          - codellama
          - codellama:7b
          - codellama:13b
          - codellama:34b
          - phi3
          - phi3:mini
          - phi3:medium
          - phi3:large
          - gemma2
          - gemma2:2b
          - gemma2:9b
          - gemma2:27b
          - neural-chat
          - neural-chat:3b
          - neural-chat:7b
          - neural-chat:20b
          - deepseek-coder
          - deepseek-coder:6.7b
          - deepseek-coder:33b
          - deepseek-llm
          - deepseek-llm:7b
          - deepseek-llm:67b
          name: Ollama
          url: https://ollama.ai/library
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      openai: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: '123123'
          base_url: https://api.openai.com/v1
          default: gpt-4o-mini
          env:
          - OPENAI_API_KEY
          models:
          - gpt-4o
          - gpt-4o-mini
          - gpt-4-turbo
          - gpt-4
          - gpt-3.5-turbo
          - gpt-3.5-turbo-16k
          name: OpenAI
          url: https://platform.openai.com/docs/models
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      openrouter: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: null
          base_url: https://openrouter.ai/api/v1
          default: openai/gpt-4o-mini
          env:
          - OPENROUTER_API_KEY
          models:
          - openai/gpt-4o
          - openai/gpt-4o-mini
          - openai/gpt-4-turbo
          - openai/gpt-3.5-turbo
          - google/gemini-2.5-pro-exp-03-25:free
          - google/gemini-2.5-flash-exp-03-25:free
          - x-ai/grok-3-beta
          - meta-llama/llama-4-maverick
          - meta-llama/llama-4-maverick:free
          - anthropic/claude-3.7-sonnet
          - anthropic/claude-3.7-sonnet:thinking
          - anthropic/claude-3.5-sonnet
          - anthropic/claude-3.5-haiku
          name: OpenRouter
          url: https://openrouter.ai/models
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      siliconflow: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: '32132123'
          base_url: https://api.siliconflow.cn/v1
          default: Qwen/Qwen3-8B
          env:
          - SILICONFLOW_API_KEY
          models:
          - Pro/deepseek-ai/DeepSeek-R1
          - Pro/deepseek-ai/DeepSeek-V3
          - Pro/deepseek-ai/DeepSeek-V3.5
          - Qwen/QwQ-32B
          - Qwen/Qwen3-8B
          - Qwen/Qwen3-32B
          - Qwen/Qwen3-72B
          - Qwen/Qwen2.5-7B-Instruct
          - Qwen/Qwen2.5-32B-Instruct
          - Qwen/Qwen2.5-72B-Instruct
          name: SiliconFlow
          url: https://cloud.siliconflow.cn/models
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      together.ai: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: null
          base_url: https://api.together.xyz/v1/
          default: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
          env:
          - TOGETHER_API_KEY
          models:
          - meta-llama/Llama-3.3-70B-Instruct-Turbo
          - meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
          - meta-llama/Llama-3.3-8B-Instruct
          - meta-llama/Llama-3.3-8B-Instruct-Free
          - deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
          - deepseek-ai/DeepSeek-V3.5
          - Qwen/QwQ-32B
          - Qwen/Qwen3-8B
          - Qwen/Qwen3-32B
          - Qwen/Qwen3-72B
          name: Together.ai
          url: https://api.together.ai/models
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
      zhipu: !!python/object:config.app_config.ModelProvider
        __dict__:
          api_key: your_zhipu_api_key_here
          base_url: https://open.bigmodel.cn/api/paas/v4/
          default: glm-4-flash
          env:
          - ZHIPUAI_API_KEY
          models:
          - glm-4
          - glm-4-plus
          - glm-4-air
          - glm-4-flash
          - glm-z1-air
          - glm-4v
          name: 智谱AI (Zhipu)
          url: https://open.bigmodel.cn/dev/api
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          default: null
          env: null
          models: null
          name: null
          url: null
        __pydantic_private__: null
    RERANKER_LIST:
      ollama/bge-reranker-base: !!python/object:config.app_config.RerankerModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/rerank
          name: bge-reranker-base
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          name: null
        __pydantic_private__: null
      ollama/bge-reranker-large: !!python/object:config.app_config.RerankerModel
        __dict__:
          api_key: null
          base_url: http://localhost:11434/api/rerank
          name: bge-reranker-large
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          base_url: null
          name: null
        __pydantic_private__: null
      siliconflow/BAAI/bge-reranker-v2-m3: !!python/object:config.app_config.RerankerModel
        __dict__:
          api_key: SILICONFLOW_API_KEY
          base_url: https://api.siliconflow.cn/v1/rerank
          name: BAAI/bge-reranker-v2-m3
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          name: null
        __pydantic_private__: null
      vllm/BAAI/bge-reranker-large: !!python/object:config.app_config.RerankerModel
        __dict__:
          api_key: no_api_key
          base_url: http://localhost:8081/v1/rerank
          name: BAAI/bge-reranker-large
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          name: null
        __pydantic_private__: null
      vllm/Qwen/Qwen3-Reranker-0.6B: !!python/object:config.app_config.RerankerModel
        __dict__:
          api_key: no_api_key
          base_url: http://localhost:8081/v1/rerank
          name: Qwen/Qwen3-Reranker-0.6B
        __pydantic_extra__: null
        __pydantic_fields_set__: !!set
          api_key: null
          base_url: null
          name: null
        __pydantic_private__: null
  __pydantic_extra__: null
  __pydantic_fields_set__: !!set
    EMBED_MODEL_INFO: null
    MODEL_NAMES: null
    RERANKER_LIST: null
  __pydantic_private__: null
model_dir: ./Huggingface
model_name: deepseek-chat
model_provider: deepseek
models_path: !!python/object/apply:pathlib.WindowsPath
- C:\
- Users
- admin
- github
- Yuxi-agent
- server
- config
- model_provider.yaml
models_private_path: !!python/object/apply:pathlib.WindowsPath
- C:\
- Users
- admin
- github
- Yuxi-agent
- server
- config
- model_provider.private.yml
provider_enabled_status:
  ark: false
  dashscope: false
  deepseek: true
  lingyiwanwu: true
  ollama: false
  openai: false
  openrouter: true
  siliconflow: false
  together.ai: false
  zhipu: false
reranker: vllm/Qwen/Qwen3-Reranker-0.6B
storage_dir: storage
tavily_api_key: tvly-3gR4ind9******JMOxw3E2LG
tavily_base_url: https://api.tavily.com
valuable_model_provider:
- openai
- deepseek
- zhipu
- siliconflow
- together.ai
- dashscope
- ark
