config_file: C:\Users\admin\github\Yuxi-agent\server\config\base_config.yaml
custom_models: []
embed_model: ollama/nomic-embed-text
enable_agent_management: true
enable_knowledge_base: true
enable_reranker: true
enable_web_search: true
model_dir: ./Huggingface
model_name: deepseek-chat
model_provider: deepseek
provider_enabled_status:
  ark: false
  dashscope: false
  deepseek: true
  lingyiwanwu: true
  openai: true
  openrouter: true
  siliconflow: true
  together.ai: false
  zhipu: false
reranker: vllm/Qwen/Qwen3-Reranker-0.6B
storage_dir: storage
tavily_api_key: tvly-3gR4ind9******JMOxw3E2LG
tavily_base_url: https://api.tavily.com
valuable_model_provider:
- openai
- deepseek
- zhipu
- siliconflow
- together.ai
- dashscope
- ark
