EMBED_MODEL_INFO:
  siliconflow/BAAI/bge-m3:
    api_key: SILICONFLOW_API_KEY
  vllm/BAAI/bge-large-zh-v1.5:
    api_key: no_api_key
  vllm/Qwen/Qwen3-Embedding-0.6B:
    api_key: no_api_key
MODEL_NAMES:
  deepseek:
    api_key: '3213123'
  ollama:
    api_key: '123'
  openai:
    api_key: '123123'
  siliconflow:
    api_key: '32132123'
  zhipu:
    api_key: 'your_zhipu_api_key_here'
RERANKER_LIST:
  siliconflow/BAAI/bge-reranker-v2-m3:
    api_key: SILICONFLOW_API_KEY
  vllm/BAAI/bge-reranker-large:
    api_key: no_api_key
  vllm/Qwen/Qwen3-Reranker-0.6B:
    api_key: no_api_key
