EMBED_MODEL_INFO:
  ollama/bge-m3:
    base_url: http://localhost:11434/api/embed
    dimension: 1024
    name: bge-m3
  ollama/nomic-embed-text:
    base_url: http://localhost:11434/api/embed
    dimension: 768
    name: nomic-embed-text
  siliconflow/BAAI/bge-m3:
    api_key: SILICONFLOW_API_KEY
    base_url: https://api.siliconflow.cn/v1/embeddings
    dimension: 1024
    name: BAAI/bge-m3
  vllm/Qwen/Qwen3-Embedding-0.6B:
    api_key: no_api_key
    base_url: http://localhost:8081/v1/embeddings
    dimension: 1024
    name: Qwen3-Embedding-0.6B
MODEL_NAMES:
  ark:
    base_url: https://ark.cn-beijing.volces.com/api/v3
    default: doubao-1-5-pro-32k-250115
    env:
    - ARK_API_KEY
    models:
    - doubao-1-5-pro-32k-250115
    - doubao-1-5-lite-32k-250115
    - deepseek-r1-250120
    name: 豆包（Ark）
    url: https://console.volcengine.com/ark/region:ark+cn-beijing/model
  dashscope:
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    default: qwen3-235b-a22b
    env:
    - DASHSCOPE_API_KEY
    models:
    - qwen-max-latest
    - qwen3-235b-a22b
    - qwen3-32b
    name: 阿里百炼 (DashScope)
    url: https://bailian.console.aliyun.com/?switchAgent=10226727&productCode=p_efm#/model-market
  deepseek:
    api_key: '3213123'
    base_url: https://api.deepseek.com/v1
    default: deepseek-chat
    env:
    - DEEPSEEK_API_KEY
    models:
    - deepseek-chat
    - deepseek-reasoner
    name: DeepSeek
    url: https://platform.deepseek.com/api-docs/zh-cn/pricing
  openai:
    base_url: https://api.openai.com/v1
    default: gpt-3.5-turbo
    env:
    - OPENAI_API_KEY
    models:
    - gpt-4
    - gpt-4o-mini
    name: OpenAI
    url: https://platform.openai.com/docs/models
  openrouter:
    base_url: https://openrouter.ai/api/v1
    default: openai/gpt-4o
    env:
    - OPENROUTER_API_KEY
    models:
    - openai/gpt-4o
    - openai/gpt-4o-mini
    - google/gemini-2.5-pro-exp-03-25:free
    - x-ai/grok-3-beta
    - meta-llama/llama-4-maverick
    - meta-llama/llama-4-maverick:free
    - anthropic/claude-3.7-sonnet
    - anthropic/claude-3.7-sonnet:thinking
    - '123213'
    name: OpenRouter
    url: https://openrouter.ai/models
  siliconflow:
    api_key: '32132123'
    base_url: https://api.siliconflow.cn/v1
    default: Qwen/Qwen3-8B
    env:
    - SILICONFLOW_API_KEY
    models:
    - Pro/deepseek-ai/DeepSeek-R1
    - Pro/deepseek-ai/DeepSeek-V3
    - Qwen/QwQ-32B
    - Qwen/Qwen3-8B
    name: SiliconFlow
    url: https://cloud.siliconflow.cn/models
  together.ai:
    base_url: https://api.together.xyz/v1/
    default: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
    env:
    - TOGETHER_API_KEY
    models:
    - meta-llama/Llama-3.3-70B-Instruct-Turbo
    - meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
    - deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
    - Qwen/QwQ-32B
    name: Together.ai
    url: https://api.together.ai/models
  zhipu:
    base_url: https://open.bigmodel.cn/api/paas/v4/
    default: glm-4-flash
    env:
    - ZHIPUAI_API_KEY
    models:
    - glm-4
    - glm-4-plus
    - glm-4-air
    - glm-4-flash
    - glm-z1-air
    name: 智谱AI (Zhipu)
    url: https://open.bigmodel.cn/dev/api
RERANKER_LIST:
  siliconflow/BAAI/bge-reranker-v2-m3:
    api_key: SILICONFLOW_API_KEY
    base_url: https://api.siliconflow.cn/v1/rerank
    name: BAAI/bge-reranker-v2-m3
  vllm/Qwen/Qwen3-Reranker-0.6B:
    api_key: no_api_key
    base_url: http://localhost:8081/v1/rerank
    name: Qwen/Qwen3-Reranker-0.6B
