####################################################
#
#  不要直接修改这个里面的文件，可能会有被覆盖的风险，
#  建议 复制一份 在 models.private.yml 中修改，
#  会自动加载
#
#####################################################

MODEL_NAMES:
  openai:
    name: OpenAI
    url: https://platform.openai.com/docs/models
    base_url: https://api.openai.com/v1
    default: gpt-4o-mini
    env:
      - OPENAI_API_KEY
    models:
      - gpt-4o
      - gpt-4o-mini
      - gpt-4-turbo
      - gpt-4
      - gpt-3.5-turbo
      - gpt-3.5-turbo-16k

  deepseek:
    name: DeepSeek
    url: https://platform.deepseek.com/api-docs/zh-cn/pricing
    base_url: https://api.deepseek.com/v1
    default: deepseek-chat
    env:
      - DEEPSEEK_API_KEY
    models:
      - deepseek-chat
      - deepseek-reasoner
      - deepseek-coder
      - deepseek-vision

  zhipu:
    name: 智谱AI (Zhipu)
    url: https://open.bigmodel.cn/dev/api
    base_url: https://open.bigmodel.cn/api/paas/v4/
    default: glm-4-flash
    env:
      - ZHIPUAI_API_KEY
    models:
      - glm-4
      - glm-4-plus
      - glm-4-air
      - glm-4-flash
      - glm-z1-air
      - glm-4v

  siliconflow:
    name: SiliconFlow
    url: https://cloud.siliconflow.cn/models
    base_url: https://api.siliconflow.cn/v1
    default: Qwen/Qwen3-8B
    env:
      - SILICONFLOW_API_KEY
    models:
      - Pro/deepseek-ai/DeepSeek-R1
      - Pro/deepseek-ai/DeepSeek-V3
      - Pro/deepseek-ai/DeepSeek-V3.5
      - Qwen/QwQ-32B
      - Qwen/Qwen3-8B
      - Qwen/Qwen3-32B
      - Qwen/Qwen3-72B
      - Qwen/Qwen2.5-7B-Instruct
      - Qwen/Qwen2.5-32B-Instruct
      - Qwen/Qwen2.5-72B-Instruct

  together.ai:
    name: Together.ai
    url: https://api.together.ai/models
    base_url: https://api.together.xyz/v1/
    default: meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
    env:
      - TOGETHER_API_KEY
    models:
      - meta-llama/Llama-3.3-70B-Instruct-Turbo
      - meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
      - meta-llama/Llama-3.3-8B-Instruct
      - meta-llama/Llama-3.3-8B-Instruct-Free
      - deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
      - deepseek-ai/DeepSeek-V3.5
      - Qwen/QwQ-32B
      - Qwen/Qwen3-8B
      - Qwen/Qwen3-32B
      - Qwen/Qwen3-72B

  dashscope:
    name: 阿里百炼 (DashScope)
    url: https://bailian.console.aliyun.com/?switchAgent=10226727&productCode=p_efm#/model-market
    base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    default: qwen-max-latest
    env:
      - DASHSCOPE_API_KEY
    models:
      - qwen-max-latest
      - qwen-max-longcontext
      - qwen3-235b-a22b
      - qwen3-32b
      - qwen2.5-7b-instruct
      - qwen2.5-32b-instruct
      - qwen2.5-72b-instruct
      - qwen2.5-7b-chat
      - qwen2.5-32b-chat
      - qwen2.5-72b-chat

  ark:
    name: 豆包（Ark）
    url: https://console.volcengine.com/ark/region:ark+cn-beijing/model
    base_url: https://ark.cn-beijing.volces.com/api/v3
    default: doubao-1-5-pro-32k-250115
    env:
      - ARK_API_KEY
    models:
      - doubao-1-5-pro-32k-250115
      - doubao-1-5-lite-32k-250115
      - doubao-1-5-pro-4k-250115
      - doubao-1-5-lite-4k-250115
      - deepseek-r1-250120

  openrouter:
    name: OpenRouter
    url: https://openrouter.ai/models
    base_url: https://openrouter.ai/api/v1
    default: openai/gpt-4o-mini
    env:
      - OPENROUTER_API_KEY
    models:
      - openai/gpt-4o
      - openai/gpt-4o-mini
      - openai/gpt-4-turbo
      - openai/gpt-3.5-turbo
      - google/gemini-2.5-pro-exp-03-25:free
      - google/gemini-2.5-flash-exp-03-25:free
      - x-ai/grok-3-beta
      - meta-llama/llama-4-maverick
      - meta-llama/llama-4-maverick:free
      - anthropic/claude-3.7-sonnet
      - anthropic/claude-3.7-sonnet:thinking
      - anthropic/claude-3.5-sonnet
      - anthropic/claude-3.5-haiku

  lingyiwanwu:
    name: 零一万物 (Lingyiwanwu)
    url: https://platform.lingyiwanwu.com/
    base_url: https://api.lingyiwanwu.com/v1
    default: yi-large
    env:
      - LINGYIWANWU_API_KEY
    models:
      - yi-large
      - yi-large-turbo
      - yi-medium
      - yi-medium-turbo
      - yi-small
      - yi-small-turbo

  ollama:
    name: Ollama
    url: https://ollama.ai/library
    base_url: http://localhost:11434/v1
    default: llama3.2
    env:
      - OLLAMA_API_KEY
    models:
      - llama3.2
      - llama3.2:3b
      - llama3.2:7b
      - llama3.2:70b
      - llama3.1
      - llama3.1:8b
      - llama3.1:70b
      - llama2
      - llama2:7b
      - llama2:13b
      - llama2:70b
      - qwen2.5
      - qwen2.5:7b
      - qwen2.5:32b
      - qwen2.5:72b
      - qwen2
      - qwen2:7b
      - qwen2:14b
      - qwen2:72b
      - mistral
      - mistral:7b
      - mistral:8x7b
      - codellama
      - codellama:7b
      - codellama:13b
      - codellama:34b
      - phi3
      - phi3:mini
      - phi3:medium
      - phi3:large
      - gemma2
      - gemma2:2b
      - gemma2:9b
      - gemma2:27b
      - neural-chat
      - neural-chat:3b
      - neural-chat:7b
      - neural-chat:20b
      - deepseek-coder
      - deepseek-coder:6.7b
      - deepseek-coder:33b
      - deepseek-llm
      - deepseek-llm:7b
      - deepseek-llm:67b

EMBED_MODEL_INFO:
  ollama/nomic-embed-text:
    name: nomic-embed-text
    base_url: http://localhost:11434/api/embed
    dimension: 768

  ollama/bge-m3:
    name: bge-m3
    base_url: http://localhost:11434/api/embed
    dimension: 1024

  ollama/bge-large-zh-v1.5:
    name: bge-large-zh-v1.5
    base_url: http://localhost:11434/api/embed
    dimension: 1024

  ollama/bge-large-en-v1.5:
    name: bge-large-en-v1.5
    base_url: http://localhost:11434/api/embed
    dimension: 1024

  ollama/bge-base-en-v1.5:
    name: bge-base-en-v1.5
    base_url: http://localhost:11434/api/embed
    dimension: 768

  ollama/bge-small-en-v1.5:
    name: bge-small-en-v1.5
    base_url: http://localhost:11434/api/embed
    dimension: 384

  siliconflow/BAAI/bge-m3:
    name: BAAI/bge-m3
    dimension: 1024
    base_url: https://api.siliconflow.cn/v1/embeddings
    api_key: SILICONFLOW_API_KEY

  vllm/Qwen/Qwen3-Embedding-0.6B:
    name: Qwen3-Embedding-0.6B
    dimension: 1024
    base_url: http://localhost:8081/v1/embeddings
    api_key: no_api_key

  vllm/BAAI/bge-large-zh-v1.5:
    name: BAAI/bge-large-zh-v1.5
    dimension: 1024
    base_url: http://localhost:8081/v1/embeddings
    api_key: no_api_key

RERANKER_LIST:
  ollama/bge-reranker-large:
    name: bge-reranker-large
    base_url: http://localhost:11434/api/rerank

  ollama/bge-reranker-base:
    name: bge-reranker-base
    base_url: http://localhost:11434/api/rerank

  siliconflow/BAAI/bge-reranker-v2-m3:
    name: BAAI/bge-reranker-v2-m3
    base_url: https://api.siliconflow.cn/v1/rerank
    api_key: SILICONFLOW_API_KEY

  vllm/Qwen/Qwen3-Reranker-0.6B:
    name: Qwen/Qwen3-Reranker-0.6B
    base_url: http://localhost:8081/v1/rerank
    api_key: no_api_key

  vllm/BAAI/bge-reranker-large:
    name: BAAI/bge-reranker-large
    base_url: http://localhost:8081/v1/rerank
    api_key: no_api_key
