config_file: C:\Users\admin\github\Yuxi-agent\server\config\base.yaml

embed_model: ollama/nomic-embed-text
enable_reranker: false
enable_web_search: true
model_dir: ./Huggingface
model_name: doubao-1-5-pro-32k-250115
model_provider: ark
reranker: siliconflow/BAAI/bge-reranker-v2-m3
storage_dir: storage
valuable_model_provider:
- openai
- deepseek
- zhipu
- siliconflow
- together.ai
- dashscope
- ark
